Repository PowerShell/DSC, pull requests merged in 2025-02, with the labels that each got.

#634 Change `reference()` to use the raw output of a resource
  dsc/Cargo.lock
  dsc/Cargo.toml
  dsc/examples/reference.dsc.yaml
  dsc/tests/dsc_reference.tests.ps1
  dsc_lib/Cargo.lock
  dsc_lib/Cargo.toml
  dsc_lib/src/configure/context.rs
  dsc_lib/src/configure/mod.rs
  dsc_lib/src/dscresources/command_resource.rs
  dsc_lib/src/functions/reference.rs
  dscecho/Cargo.lock
  osinfo/Cargo.lock
  process/Cargo.lock
  registry/Cargo.lock
  runcommandonset/Cargo.lock
  security_context_lib/Cargo.lock
  tools/dsctest/Cargo.lock
  tools/test_group_resource/Cargo.lock
  tree-sitter-dscexpression/Cargo.lock
  tree-sitter-dscexpression/Cargo.toml
  y2j/Cargo.lock
Labels: Doc-Impact

#647 Fix config size limit by validating modules in cache
  powershell-adapter/Tests/powershellgroup.config.tests.ps1
  powershell-adapter/psDscAdapter/powershell.resource.ps1
Labels: Backport-Needed

#644 Fix progress display when using JSON, add None option; exhance progress schema
  dsc/Cargo.lock
  dsc/src/args.rs
  dsc/src/main.rs
  dsc/src/subcommand.rs
  dsc/tests/dsc_args.tests.ps1
  dsc/tests/dsc_config_get.tests.ps1
  dsc/tests/dsc_resource_list.tests.ps1
  dsc_lib/Cargo.lock
  dsc_lib/Cargo.toml
  dsc_lib/locales/en-us.toml
  dsc_lib/src/configure/mod.rs
  dsc_lib/src/discovery/command_discovery.rs
  dsc_lib/src/discovery/discovery_trait.rs
  dsc_lib/src/discovery/mod.rs
  dsc_lib/src/lib.rs
  dsc_lib/src/progress.rs
  dsc_lib/src/util.rs
  tools/test_group_resource/Cargo.lock
Labels: Doc-Impact, Backport-Needed
